### ISSUE TITLE
[BUG] Genshin Impact Global not refreshing events, notices and info

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#23]
Like the title says, Genshin Global fails to get Events, Notices and Info
![image](https://user-images.githubusercontent.com/12277635/191061610-39934991-45af-46f7-838a-0857230187d4.png)
![image](https://user-images.githubusercontent.com/12277635/191061653-278029b2-3d6e-443d-b92d-e1de0a90aec2.png)
![image](https://user-images.githubusercontent.com/12277635/191061683-8f0b3980-9f2a-4454-aa40-f52ece1d3d00.png)

**Comment by neon-nyan** [comment]
Uhm, I don't see it as a problem and this is actually an "**expected**" behaviour of the launcher when the API doesn't have Events or Info or other section to show on and will be replaced with Paimon instead.
As you can see in the screenshot below, the official launcher (left) doesn't have Events and Info to show on.

![image](https://user-images.githubusercontent.com/30566970/191531255-ab767700-3a47-4fe0-ba97-90b627891a04.png)

Btw, I'm using the latest version of the official launcher, which is 2.19.0.0

![image](https://user-images.githubusercontent.com/30566970/191532878-a599b704-7e23-41da-956e-569dd18c6ab4.png)

Since this is not actually a bug, I will go ahead to close this issue instead.
