### ISSUE TITLE
With the new UI update there are some inconsistencies

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#33]
As per title
Issue no.1
![image](https://user-images.githubusercontent.com/12277635/195865087-dccd5482-6835-428d-b1eb-6df4451a7406.png)
Issue no.2
![image](https://user-images.githubusercontent.com/12277635/195865868-cf8184e7-c573-4738-afa0-89ff8fbd7747.png)
This is the issue magnified
![image](https://user-images.githubusercontent.com/12277635/195865920-e05b945c-45ac-4f11-9aa4-42695a991aa5.png)

**Comment by neon-nyan** [comment]
Uhm, let me get it straight:

1. The Shadow doesn't follow the image button
2. The border of Navigation panel has 1px Gap Horizontally and Vertically

Is that right?

For Issue No. 2, I've made a fix by giving the margin with -1px each. I think (again) this is an issue with the WinUI 3 1.2-pre2 runtime (Since we have no visual problem with previous version, which is using WinUI 3 1.1.4).

Anyway, I'm still finding a way to get the shadow to follow the image button for No. 1 because ``SharedShadow`` will just accept basic shapes like Rectangles and Rounded-rectangel

**Comment by neon-nyan** [comment]
This issue should've been addressed in these commits: https://github.com/neon-nyan/CollapseLauncher/commit/e14f81caf97ca23a7fd3f99e2a7f13cdbb02e9fa https://github.com/neon-nyan/CollapseLauncher/commit/1497f0d124a6b927bafb3c63c81b92510e22d972
You can try test it out and let me know if the issue is fixed or not.

**Comment by muscularcandy67** [comment]
I can confirm the issues are now resolved so I'm closing this issue. Thanks for the good work!
